name: Build APK
on: push
jobs:
  hosting:
    name: Bluid Flutter App
    runs-on: ubuntu-latest
    steps:
      # Checkout Repository
      - uses: actions/checkout@v2
      
      # Install Flutter command
      - uses: subosito/flutter-action@v1
        with: 
          channel: 'stable'
          
      # Build Flutter App
      - name: Build Flutter App
        run: 
          flutter pub get
          flutter build apk
      
    
  
